spring.application.name=frontend

server.port=10340

server.forward-headers-strategy=framework

eureka.client.service-url.defaultZone=http://localhost:10344/eureka,http://localhost:10345/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

custom.security.jwt.access-token-expiration=3600
custom.security.jwt.refresh-token-expiration=604800

logging.level.com.nhnacademy.frontend=debug


logging.level.feign=debug
logging.level.com.nhnacademy.frontend.review.adapter=debug


payco.client-id=3RD6VrfE1Y90Vo53r_dIkwf
payco.redirect-uri=https://bookstore-beansolid.store/auth/login/payco/callback


spring.config.import=optional:configserver:
spring.cloud.config.discovery.enabled=true
spring.cloud.config.discovery.service-id=config-server
spring.cloud.config.name=redis,payments, minio
spring.cloud.config.profile=default

# MinIO 리뷰사진 저장소 이름(bucket) 설정
spring.minio.review.image.bucket.name=beansolid-review-image

management.endpoints.web.exposure.include=env,health


spring.mvc.hiddenmethod.filter.enabled=true

spring.cloud.openfeign.httpclient.ok-http.read-timeout=60s
spring.cloud.openfeign.httpclient.connection-timeout=20000

spring.data.redis.host=10.116.64.14
spring.data.redis.port=6379
spring.data.redis.database=310